pages = [{"l":"index.html#","e":false,"i":"","n":"Scurry","t":"Scurry","d":"","k":"static","x":""},
{"l":"scurry/http.html#","e":false,"i":"","n":"scurry.http","t":"scurry.http","d":"","k":"package","x":""},
{"l":"scurry/http.html#BodyWriter-0","e":false,"i":"","n":"BodyWriter","t":"BodyWriter = BodyWriter","d":"scurry.http","k":"type","x":""},
{"l":"scurry/http/request.html#","e":false,"i":"","n":"scurry.http.request","t":"scurry.http.request","d":"","k":"package","x":""},
{"l":"scurry/http/request/Connect.html#","e":false,"i":"","n":"Connect","t":"Connect extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Connect.html#<init>-3a3","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Connect","k":"def","x":""},
{"l":"scurry/http/request/Delete.html#","e":false,"i":"","n":"Delete","t":"Delete extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Delete.html#<init>-fd2","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Delete","k":"def","x":""},
{"l":"scurry/http/request/Get.html#","e":false,"i":"","n":"Get","t":"Get extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Get.html#<init>-fffffe8f","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Get","k":"def","x":""},
{"l":"scurry/http/request/Head.html#","e":false,"i":"","n":"Head","t":"Head extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Head.html#<init>-5c7","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Head","k":"def","x":""},
{"l":"scurry/http/request/Options.html#","e":false,"i":"","n":"Options","t":"Options extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Options.html#<init>-fffff157","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Options","k":"def","x":""},
{"l":"scurry/http/request/Patch.html#","e":false,"i":"","n":"Patch","t":"Patch extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Patch.html#<init>-541","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Patch","k":"def","x":""},
{"l":"scurry/http/request/Post.html#","e":false,"i":"","n":"Post","t":"Post extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Post.html#<init>-87","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Post","k":"def","x":""},
{"l":"scurry/http/request/Put.html#","e":false,"i":"","n":"Put","t":"Put extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Put.html#<init>-fffff248","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Put","k":"def","x":""},
{"l":"scurry/http/request/Trace.html#","e":false,"i":"","n":"Trace","t":"Trace extends HttpRequest","d":"scurry.http.request","k":"class","x":""},
{"l":"scurry/http/request/Trace.html#<init>-63e","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.request.Trace","k":"def","x":""},
{"l":"scurry/http/response.html#","e":false,"i":"","n":"scurry.http.response","t":"scurry.http.response","d":"","k":"package","x":""},
{"l":"scurry/http/response/Accepted.html#","e":false,"i":"","n":"Accepted","t":"Accepted extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Accepted.html#<init>-c0c","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Accepted","k":"def","x":""},
{"l":"scurry/http/response/BadGateway.html#","e":false,"i":"","n":"BadGateway","t":"BadGateway extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/BadGateway.html#<init>-9a4","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.BadGateway","k":"def","x":""},
{"l":"scurry/http/response/BadRequest.html#","e":false,"i":"","n":"BadRequest","t":"BadRequest extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/BadRequest.html#<init>-fffff5ef","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.BadRequest","k":"def","x":""},
{"l":"scurry/http/response/Conflict.html#","e":false,"i":"","n":"Conflict","t":"Conflict extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Conflict.html#<init>-fffff837","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Conflict","k":"def","x":""},
{"l":"scurry/http/response/Continue.html#","e":false,"i":"","n":"Continue","t":"Continue extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Continue.html#<init>-fffff90c","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Continue","k":"def","x":""},
{"l":"scurry/http/response/Created.html#","e":false,"i":"","n":"Created","t":"Created extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Created.html#<init>-1e3","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Created","k":"def","x":""},
{"l":"scurry/http/response/EarlyHints.html#","e":false,"i":"","n":"EarlyHints","t":"EarlyHints extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/EarlyHints.html#<init>-fffff84e","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.EarlyHints","k":"def","x":""},
{"l":"scurry/http/response/ExpectationFailed.html#","e":false,"i":"","n":"ExpectationFailed","t":"ExpectationFailed extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/ExpectationFailed.html#<init>-fffff6d4","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.ExpectationFailed","k":"def","x":""},
{"l":"scurry/http/response/Forbidden.html#","e":false,"i":"","n":"Forbidden","t":"Forbidden extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Forbidden.html#<init>-fffffc34","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Forbidden","k":"def","x":""},
{"l":"scurry/http/response/Found.html#","e":false,"i":"","n":"Found","t":"Found extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Found.html#<init>-fffffd3d","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Found","k":"def","x":""},
{"l":"scurry/http/response/GatewayTimeout.html#","e":false,"i":"","n":"GatewayTimeout","t":"GatewayTimeout extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/GatewayTimeout.html#<init>-fffff722","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.GatewayTimeout","k":"def","x":""},
{"l":"scurry/http/response/Gone.html#","e":false,"i":"","n":"Gone","t":"Gone extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Gone.html#<init>-784","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Gone","k":"def","x":""},
{"l":"scurry/http/response/HttpVersionNotSupported.html#","e":false,"i":"","n":"HttpVersionNotSupported","t":"HttpVersionNotSupported extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/HttpVersionNotSupported.html#<init>-366","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.HttpVersionNotSupported","k":"def","x":""},
{"l":"scurry/http/response/InternalServerError.html#","e":false,"i":"","n":"InternalServerError","t":"InternalServerError extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/InternalServerError.html#<init>-3","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.InternalServerError","k":"def","x":""},
{"l":"scurry/http/response/LengthRequired.html#","e":false,"i":"","n":"LengthRequired","t":"LengthRequired extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/LengthRequired.html#<init>-fffff14a","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.LengthRequired","k":"def","x":""},
{"l":"scurry/http/response/MethodNotAllowed.html#","e":false,"i":"","n":"MethodNotAllowed","t":"MethodNotAllowed extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/MethodNotAllowed.html#<init>-a7b","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.MethodNotAllowed","k":"def","x":""},
{"l":"scurry/http/response/MovedPermanently.html#","e":false,"i":"","n":"MovedPermanently","t":"MovedPermanently extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/MovedPermanently.html#<init>-16d","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.MovedPermanently","k":"def","x":""},
{"l":"scurry/http/response/MultipleChoices.html#","e":false,"i":"","n":"MultipleChoices","t":"MultipleChoices extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/MultipleChoices.html#<init>-ebd","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.MultipleChoices","k":"def","x":""},
{"l":"scurry/http/response/NetworkAuthenticationRequired.html#","e":false,"i":"","n":"NetworkAuthenticationRequired","t":"NetworkAuthenticationRequired extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NetworkAuthenticationRequired.html#<init>-fffffec0","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NetworkAuthenticationRequired","k":"def","x":""},
{"l":"scurry/http/response/NoContent.html#","e":false,"i":"","n":"NoContent","t":"NoContent extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NoContent.html#<init>-fffff3b3","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NoContent","k":"def","x":""},
{"l":"scurry/http/response/NonAuthoritativeInformation.html#","e":false,"i":"","n":"NonAuthoritativeInformation","t":"NonAuthoritativeInformation extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NonAuthoritativeInformation.html#<init>-ffffff85","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NonAuthoritativeInformation","k":"def","x":""},
{"l":"scurry/http/response/NotAcceptable.html#","e":false,"i":"","n":"NotAcceptable","t":"NotAcceptable extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NotAcceptable.html#<init>-fffffc50","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NotAcceptable","k":"def","x":""},
{"l":"scurry/http/response/NotFound.html#","e":false,"i":"","n":"NotFound","t":"NotFound extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NotFound.html#<init>-4d4","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NotFound","k":"def","x":""},
{"l":"scurry/http/response/NotImplemented.html#","e":false,"i":"","n":"NotImplemented","t":"NotImplemented extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NotImplemented.html#<init>-4d4","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NotImplemented","k":"def","x":""},
{"l":"scurry/http/response/NotModified.html#","e":false,"i":"","n":"NotModified","t":"NotModified extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/NotModified.html#<init>-fffffc37","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.NotModified","k":"def","x":""},
{"l":"scurry/http/response/Ok.html#","e":false,"i":"","n":"Ok","t":"Ok extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Ok.html#<init>-a01","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Ok","k":"def","x":""},
{"l":"scurry/http/response/PartialContent.html#","e":false,"i":"","n":"PartialContent","t":"PartialContent extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/PartialContent.html#<init>-c5d","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.PartialContent","k":"def","x":""},
{"l":"scurry/http/response/PayloadTooLarge.html#","e":false,"i":"","n":"PayloadTooLarge","t":"PayloadTooLarge extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/PayloadTooLarge.html#<init>-df0","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.PayloadTooLarge","k":"def","x":""},
{"l":"scurry/http/response/PaymentRequired.html#","e":false,"i":"","n":"PaymentRequired","t":"PaymentRequired extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/PaymentRequired.html#<init>-3c0","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.PaymentRequired","k":"def","x":""},
{"l":"scurry/http/response/PermanentRedirect.html#","e":false,"i":"","n":"PermanentRedirect","t":"PermanentRedirect extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/PermanentRedirect.html#<init>-fffff7e5","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.PermanentRedirect","k":"def","x":""},
{"l":"scurry/http/response/PreconditionFailed.html#","e":false,"i":"","n":"PreconditionFailed","t":"PreconditionFailed extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/PreconditionFailed.html#<init>-25a","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.PreconditionFailed","k":"def","x":""},
{"l":"scurry/http/response/PreconditionRequired.html#","e":false,"i":"","n":"PreconditionRequired","t":"PreconditionRequired extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/PreconditionRequired.html#<init>-fffff67c","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.PreconditionRequired","k":"def","x":""},
{"l":"scurry/http/response/ProxyAuthenticationRequired.html#","e":false,"i":"","n":"ProxyAuthenticationRequired","t":"ProxyAuthenticationRequired extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/ProxyAuthenticationRequired.html#<init>-fffff1c0","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.ProxyAuthenticationRequired","k":"def","x":""},
{"l":"scurry/http/response/RangeNotSatisfiable.html#","e":false,"i":"","n":"RangeNotSatisfiable","t":"RangeNotSatisfiable extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/RangeNotSatisfiable.html#<init>-fffff872","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.RangeNotSatisfiable","k":"def","x":""},
{"l":"scurry/http/response/RequestHeaderFieldsTooLarge.html#","e":false,"i":"","n":"RequestHeaderFieldsTooLarge","t":"RequestHeaderFieldsTooLarge extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/RequestHeaderFieldsTooLarge.html#<init>-cb7","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.RequestHeaderFieldsTooLarge","k":"def","x":""},
{"l":"scurry/http/response/RequestTimeout.html#","e":false,"i":"","n":"RequestTimeout","t":"RequestTimeout extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/RequestTimeout.html#<init>-fffff077","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.RequestTimeout","k":"def","x":""},
{"l":"scurry/http/response/ResetContent.html#","e":false,"i":"","n":"ResetContent","t":"ResetContent extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/ResetContent.html#<init>-fffffa0f","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.ResetContent","k":"def","x":""},
{"l":"scurry/http/response/SeeOther.html#","e":false,"i":"","n":"SeeOther","t":"SeeOther extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/SeeOther.html#<init>-ae2","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.SeeOther","k":"def","x":""},
{"l":"scurry/http/response/ServiceUnavailable.html#","e":false,"i":"","n":"ServiceUnavailable","t":"ServiceUnavailable extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/ServiceUnavailable.html#<init>-880","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.ServiceUnavailable","k":"def","x":""},
{"l":"scurry/http/response/SwitchingProtocols.html#","e":false,"i":"","n":"SwitchingProtocols","t":"SwitchingProtocols extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/SwitchingProtocols.html#<init>-672","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.SwitchingProtocols","k":"def","x":""},
{"l":"scurry/http/response/TemporaryRedirect.html#","e":false,"i":"","n":"TemporaryRedirect","t":"TemporaryRedirect extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/TemporaryRedirect.html#<init>-e88","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.TemporaryRedirect","k":"def","x":""},
{"l":"scurry/http/response/TooEarly.html#","e":false,"i":"","n":"TooEarly","t":"TooEarly extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/TooEarly.html#<init>-fffff6d4","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.TooEarly","k":"def","x":""},
{"l":"scurry/http/response/TooManyRequests.html#","e":false,"i":"","n":"TooManyRequests","t":"TooManyRequests extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/TooManyRequests.html#<init>-ab2","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.TooManyRequests","k":"def","x":""},
{"l":"scurry/http/response/Unauthorized.html#","e":false,"i":"","n":"Unauthorized","t":"Unauthorized extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/Unauthorized.html#<init>-fffffad9","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.Unauthorized","k":"def","x":""},
{"l":"scurry/http/response/UnavailableForLegalReasons.html#","e":false,"i":"","n":"UnavailableForLegalReasons","t":"UnavailableForLegalReasons extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/UnavailableForLegalReasons.html#<init>-7d4","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.UnavailableForLegalReasons","k":"def","x":""},
{"l":"scurry/http/response/UnprocessableEntity.html#","e":false,"i":"","n":"UnprocessableEntity","t":"UnprocessableEntity extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/UnprocessableEntity.html#<init>-fffff28e","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.UnprocessableEntity","k":"def","x":""},
{"l":"scurry/http/response/UnsupportedMediaType.html#","e":false,"i":"","n":"UnsupportedMediaType","t":"UnsupportedMediaType extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/UnsupportedMediaType.html#<init>-fffff76e","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.UnsupportedMediaType","k":"def","x":""},
{"l":"scurry/http/response/UpgradeRequired.html#","e":false,"i":"","n":"UpgradeRequired","t":"UpgradeRequired extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/UpgradeRequired.html#<init>-5d6","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.UpgradeRequired","k":"def","x":""},
{"l":"scurry/http/response/UriTooLong.html#","e":false,"i":"","n":"UriTooLong","t":"UriTooLong extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/UriTooLong.html#<init>-a09","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.UriTooLong","k":"def","x":""},
{"l":"scurry/http/response/UseProxy.html#","e":false,"i":"","n":"UseProxy","t":"UseProxy extends HttpResponse","d":"scurry.http.response","k":"class","x":""},
{"l":"scurry/http/response/UseProxy.html#<init>-fffffd8c","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.response.UseProxy","k":"def","x":""},
{"l":"scurry/http/settings.html#","e":false,"i":"","n":"scurry.http.settings","t":"scurry.http.settings","d":"","k":"package","x":""},
{"l":"scurry/http/settings/ClientSettings.html#","e":false,"i":"","n":"ClientSettings","t":"ClientSettings","d":"scurry.http.settings","k":"trait","x":""},
{"l":"scurry/http/settings/ClientSettings.html#getAccept-a5e","e":false,"i":"","n":"getAccept","t":"getAccept(): List[String]","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ClientSettings.html#getAcceptEncoding-a5e","e":false,"i":"","n":"getAcceptEncoding","t":"getAcceptEncoding(): List[String]","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ClientSettings.html#getBufferSize-ffffff27","e":false,"i":"","n":"getBufferSize","t":"getBufferSize(): Int","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ClientSettings.html#getContinueTimeout-ffffff27","e":false,"i":"","n":"getContinueTimeout","t":"getContinueTimeout(): Int","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ClientSettings.html#getReadTimeout-ffffff27","e":false,"i":"","n":"getReadTimeout","t":"getReadTimeout(): Int","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ClientSettings.html#isCookieStoreEnabled-fffff760","e":false,"i":"","n":"isCookieStoreEnabled","t":"isCookieStoreEnabled(): Boolean","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ClientSettings.html#isKeepAliveEnabled-fffff760","e":false,"i":"","n":"isKeepAliveEnabled","t":"isKeepAliveEnabled(): Boolean","d":"scurry.http.settings.ClientSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#","e":false,"i":"","n":"ServerSettings","t":"ServerSettings","d":"scurry.http.settings","k":"trait","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getBacklogSize-ffffff27","e":false,"i":"","n":"getBacklogSize","t":"getBacklogSize(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getBufferSize-ffffff27","e":false,"i":"","n":"getBufferSize","t":"getBufferSize(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getHeaderLimit-ffffff27","e":false,"i":"","n":"getHeaderLimit","t":"getHeaderLimit(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getHost-665","e":false,"i":"","n":"getHost","t":"getHost(): String","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getPoolSize-ffffff27","e":false,"i":"","n":"getPoolSize","t":"getPoolSize(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getPort-ffffff27","e":false,"i":"","n":"getPort","t":"getPort(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getQueueSize-ffffff27","e":false,"i":"","n":"getQueueSize","t":"getQueueSize(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#getReadTimeout-ffffff27","e":false,"i":"","n":"getReadTimeout","t":"getReadTimeout(): Int","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#isKeepAliveEnabled-fffff760","e":false,"i":"","n":"isKeepAliveEnabled","t":"isKeepAliveEnabled(): Boolean","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/settings/ServerSettings.html#isSslEnabled-fffff760","e":false,"i":"","n":"isSslEnabled","t":"isSslEnabled(): Boolean","d":"scurry.http.settings.ServerSettings","k":"def","x":""},
{"l":"scurry/http/Body.html#","e":false,"i":"","n":"Body","t":"Body","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/Body.html#drain-fffffa90","e":false,"i":"","n":"drain","t":"drain(length: Long): Unit","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#drain-fffffe0d","e":false,"i":"","n":"drain","t":"drain(sink: OutputStream, length: Long): Unit","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#isKnownEmpty-fffff760","e":false,"i":"","n":"isKnownEmpty","t":"isKnownEmpty(): Boolean","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toBytes-4d9","e":false,"i":"","n":"toBytes","t":"toBytes(length: Int): Array[Byte]","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toFile-974","e":false,"i":"","n":"toFile","t":"toFile(dest: File, length: Long): File","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toInputStream-fffff78a","e":false,"i":"","n":"toInputStream","t":"toInputStream(length: Long): InputStream","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toMultipart-b84","e":false,"i":"","n":"toMultipart","t":"toMultipart(dest: File, length: Long): Multipart","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toMultipart-aab","e":false,"i":"","n":"toMultipart","t":"toMultipart(dest: Path, length: Long): Multipart","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toPath-866","e":false,"i":"","n":"toPath","t":"toPath(dest: Path, length: Long): Path","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toQueryString-fffffa26","e":false,"i":"","n":"toQueryString","t":"toQueryString(length: Int): QueryString","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toReader-ae2","e":false,"i":"","n":"toReader","t":"toReader(length: Long): BufferedReader","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Body.html#toString-78c","e":false,"i":"","n":"toString","t":"toString(length: Int): String","d":"scurry.http.Body","k":"def","x":""},
{"l":"scurry/http/Cookies.html#","e":false,"i":"","n":"Cookies","t":"Cookies","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/Cookies.html#get-fffff5f8","e":false,"i":"","n":"get","t":"get(name: String): AnyRef","d":"scurry.http.Cookies","k":"def","x":""},
{"l":"scurry/http/Cookies.html#isEmpty-fffff760","e":false,"i":"","n":"isEmpty","t":"isEmpty(): Boolean","d":"scurry.http.Cookies","k":"def","x":""},
{"l":"scurry/http/Cookies.html#iterator-22e","e":false,"i":"","n":"iterator","t":"iterator(): Iterator[AnyRef]","d":"scurry.http.Cookies","k":"def","x":""},
{"l":"scurry/http/Cookies.html#size-ffffff27","e":false,"i":"","n":"size","t":"size(): Int","d":"scurry.http.Cookies","k":"def","x":""},
{"l":"scurry/http/Cookies.html#<init>-fffff86e","e":false,"i":"","n":"this","t":"this(cookies: Array[AnyRef])","d":"scurry.http.Cookies","k":"def","x":""},
{"l":"scurry/http/Headers.html#","e":false,"i":"","n":"Headers","t":"Headers","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/Headers.html#get-fffff2ca","e":false,"i":"","n":"get","t":"get(name: String): String","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#getDate-fffffb13","e":false,"i":"","n":"getDate","t":"getDate(name: String): Date","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#getInstant-fffffc27","e":false,"i":"","n":"getInstant","t":"getInstant(name: String): Instant","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#getInteger-5a5","e":false,"i":"","n":"getInteger","t":"getInteger(name: String): Integer","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#getLong-fffff375","e":false,"i":"","n":"getLong","t":"getLong(name: String): Long","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#getValues-fffffc03","e":false,"i":"","n":"getValues","t":"getValues(name: String): List[String]","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#isEmpty-fffff760","e":false,"i":"","n":"isEmpty","t":"isEmpty(): Boolean","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#iterator-22e","e":false,"i":"","n":"iterator","t":"iterator(): Iterator[AnyRef]","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#size-ffffff27","e":false,"i":"","n":"size","t":"size(): Int","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/Headers.html#<init>-fffffe9e","e":false,"i":"","n":"this","t":"this(fields: Map[String, AnyRef])","d":"scurry.http.Headers","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#","e":false,"i":"","n":"HttpClient","t":"HttpClient","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/HttpClient.html#delete-be0","e":false,"i":"","n":"delete","t":"delete[T](req: AnyRef, handler: HttpResponse => T): T","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#get-be0","e":false,"i":"","n":"get","t":"get[T](req: AnyRef, handler: HttpResponse => T): T","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#getCookies-fffff32c","e":false,"i":"","n":"getCookies","t":"getCookies(): PersistentCookies","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#getSettings-fffff6ad","e":false,"i":"","n":"getSettings","t":"getSettings(): ClientSettings","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#incoming-fffff790","e":false,"i":"","n":"incoming","t":"incoming(filter: HttpResponse => AnyRef): this.type","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#outgoing-fffff790","e":false,"i":"","n":"outgoing","t":"outgoing(filter: HttpRequest => AnyRef): this.type","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#post-be0","e":false,"i":"","n":"post","t":"post[T](req: AnyRef, handler: HttpResponse => T): T","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#put-be0","e":false,"i":"","n":"put","t":"put[T](req: AnyRef, handler: HttpResponse => T): T","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#send-be0","e":false,"i":"","n":"send","t":"send[T](req: AnyRef, handler: HttpResponse => T): T","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#<init>-fffffc5b","e":false,"i":"","n":"this","t":"this(settings: Map[String, AnyRef])","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#<init>-fffff5bf","e":false,"i":"","n":"this","t":"this()","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpClient.html#websocket-be0","e":false,"i":"","n":"websocket","t":"websocket[T](req: AnyRef, handler: WebSocket => T): T","d":"scurry.http.HttpClient","k":"def","x":""},
{"l":"scurry/http/HttpMessage.html#","e":false,"i":"","n":"HttpMessage","t":"HttpMessage","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/HttpMessage.html#getBody-5ee","e":false,"i":"","n":"getBody","t":"getBody(): Body","d":"scurry.http.HttpMessage","k":"def","x":""},
{"l":"scurry/http/HttpMessage.html#getCookies-fffff2c3","e":false,"i":"","n":"getCookies","t":"getCookies(): Cookies","d":"scurry.http.HttpMessage","k":"def","x":""},
{"l":"scurry/http/HttpMessage.html#getHeaders-ffffffba","e":false,"i":"","n":"getHeaders","t":"getHeaders(): Headers","d":"scurry.http.HttpMessage","k":"def","x":""},
{"l":"scurry/http/HttpMessage.html#getHttpVersion-665","e":false,"i":"","n":"getHttpVersion","t":"getHttpVersion(): String","d":"scurry.http.HttpMessage","k":"def","x":""},
{"l":"scurry/http/HttpMessage.html#getStartLine-665","e":false,"i":"","n":"getStartLine","t":"getStartLine(): String","d":"scurry.http.HttpMessage","k":"def","x":""},
{"l":"scurry/http/HttpRequest.html#","e":false,"i":"","n":"HttpRequest","t":"HttpRequest extends HttpMessage","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/HttpRequest.html#getCookies-fffff2c3","e":false,"i":"","n":"getCookies","t":"getCookies(): Cookies","d":"scurry.http.HttpRequest","k":"def","x":""},
{"l":"scurry/http/HttpRequest.html#getMethod-665","e":false,"i":"","n":"getMethod","t":"getMethod(): String","d":"scurry.http.HttpRequest","k":"def","x":""},
{"l":"scurry/http/HttpRequest.html#getPath-665","e":false,"i":"","n":"getPath","t":"getPath(): String","d":"scurry.http.HttpRequest","k":"def","x":""},
{"l":"scurry/http/HttpRequest.html#getQuery-fffff52d","e":false,"i":"","n":"getQuery","t":"getQuery(): QueryString","d":"scurry.http.HttpRequest","k":"def","x":""},
{"l":"scurry/http/HttpRequest.html#getTarget-665","e":false,"i":"","n":"getTarget","t":"getTarget(): String","d":"scurry.http.HttpRequest","k":"def","x":""},
{"l":"scurry/http/HttpRequest.html#<init>-fffffbff","e":false,"i":"","n":"this","t":"this(req: Map[String, AnyRef])","d":"scurry.http.HttpRequest","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#","e":false,"i":"","n":"HttpResponse","t":"HttpResponse extends HttpMessage","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/HttpResponse.html#getCookies-fffff2c3","e":false,"i":"","n":"getCookies","t":"getCookies(): Cookies","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#getReasonPhrase-665","e":false,"i":"","n":"getReasonPhrase","t":"getReasonPhrase(): String","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#getStatusCode-ffffff27","e":false,"i":"","n":"getStatusCode","t":"getStatusCode(): Int","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#isClientError-fffff760","e":false,"i":"","n":"isClientError","t":"isClientError(): Boolean","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#isInformational-fffff760","e":false,"i":"","n":"isInformational","t":"isInformational(): Boolean","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#isRedirection-fffff760","e":false,"i":"","n":"isRedirection","t":"isRedirection(): Boolean","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#isServerError-fffff760","e":false,"i":"","n":"isServerError","t":"isServerError(): Boolean","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#isSuccessful-fffff760","e":false,"i":"","n":"isSuccessful","t":"isSuccessful(): Boolean","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpResponse.html#<init>-fffff8d1","e":false,"i":"","n":"this","t":"this(res: Map[String, AnyRef])","d":"scurry.http.HttpResponse","k":"def","x":""},
{"l":"scurry/http/HttpServer.html#","e":false,"i":"","n":"HttpServer","t":"HttpServer extends Router","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/HttpServer.html#getSettings-fffffa25","e":false,"i":"","n":"getSettings","t":"getSettings(): ServerSettings","d":"scurry.http.HttpServer","k":"def","x":""},
{"l":"scurry/http/HttpServer.html#isRunning-fffff760","e":false,"i":"","n":"isRunning","t":"isRunning(): Boolean","d":"scurry.http.HttpServer","k":"def","x":""},
{"l":"scurry/http/HttpServer.html#start-94c","e":false,"i":"","n":"start","t":"start(): Unit","d":"scurry.http.HttpServer","k":"def","x":""},
{"l":"scurry/http/HttpServer.html#stop-94c","e":false,"i":"","n":"stop","t":"stop(): Unit","d":"scurry.http.HttpServer","k":"def","x":""},
{"l":"scurry/http/HttpServer.html#<init>-fffff7d3","e":false,"i":"","n":"this","t":"this(settings: Map[String, AnyRef])","d":"scurry.http.HttpServer","k":"def","x":""},
{"l":"scurry/http/Multipart.html#","e":false,"i":"","n":"Multipart","t":"Multipart","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/Multipart.html#addPart-82d","e":false,"i":"","n":"addPart","t":"addPart(part: AnyRef): this.type","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#addParts-695","e":false,"i":"","n":"addParts","t":"addParts(parts: AnyRef*): this.type","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#close-fffff7e0","e":false,"i":"","n":"close","t":"close(): this.type","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#getPart-fffff5f8","e":false,"i":"","n":"getPart","t":"getPart(name: String): AnyRef","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#getParts-fffffc03","e":false,"i":"","n":"getParts","t":"getParts(name: String): List[AnyRef]","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#isClosed-fffff760","e":false,"i":"","n":"isClosed","t":"isClosed(): Boolean","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#iterator-22e","e":false,"i":"","n":"iterator","t":"iterator(): Iterator[AnyRef]","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/Multipart.html#<init>-ecb","e":false,"i":"","n":"this","t":"this(parts: Array[AnyRef])","d":"scurry.http.Multipart","k":"def","x":""},
{"l":"scurry/http/PersistentCookies.html#","e":false,"i":"","n":"PersistentCookies","t":"PersistentCookies","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/PersistentCookies.html#clear-fffff7cc","e":false,"i":"","n":"clear","t":"clear(expiredOnly: Boolean): this.type","d":"scurry.http.PersistentCookies","k":"def","x":""},
{"l":"scurry/http/PersistentCookies.html#get-fffff6b1","e":false,"i":"","n":"get","t":"get(target: AnyRef): List[AnyRef]","d":"scurry.http.PersistentCookies","k":"def","x":""},
{"l":"scurry/http/PersistentCookies.html#isEmpty-fffff760","e":false,"i":"","n":"isEmpty","t":"isEmpty(): Boolean","d":"scurry.http.PersistentCookies","k":"def","x":""},
{"l":"scurry/http/PersistentCookies.html#iterator-22e","e":false,"i":"","n":"iterator","t":"iterator(): Iterator[AnyRef]","d":"scurry.http.PersistentCookies","k":"def","x":""},
{"l":"scurry/http/PersistentCookies.html#size-ffffff27","e":false,"i":"","n":"size","t":"size(): Int","d":"scurry.http.PersistentCookies","k":"def","x":""},
{"l":"scurry/http/QueryString.html#","e":false,"i":"","n":"QueryString","t":"QueryString","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/QueryString.html#get-fffff2ca","e":false,"i":"","n":"get","t":"get(name: String): String","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#getInteger-5a5","e":false,"i":"","n":"getInteger","t":"getInteger(name: String): Integer","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#getLong-fffff375","e":false,"i":"","n":"getLong","t":"getLong(name: String): Long","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#getNames-a5e","e":false,"i":"","n":"getNames","t":"getNames(): List[String]","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#getValues-fffffc03","e":false,"i":"","n":"getValues","t":"getValues(name: String): List[String]","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#isEmpty-fffff760","e":false,"i":"","n":"isEmpty","t":"isEmpty(): Boolean","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#iterator-22e","e":false,"i":"","n":"iterator","t":"iterator(): Iterator[AnyRef]","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#<init>-fffffd28","e":false,"i":"","n":"this","t":"this(query: String)","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/QueryString.html#<init>-fffff211","e":false,"i":"","n":"this","t":"this(params: Map[String, AnyRef])","d":"scurry.http.QueryString","k":"def","x":""},
{"l":"scurry/http/Router.html#","e":false,"i":"","n":"Router","t":"Router","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/Router.html#delete-d21","e":false,"i":"","n":"delete","t":"delete(path: String, handler: HttpRequest => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#fileserver-fffffbf8","e":false,"i":"","n":"fileserver","t":"fileserver(path: String, source: AnyRef, defaults: String*): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#get-d21","e":false,"i":"","n":"get","t":"get(path: String, handler: HttpRequest => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#getAbsolutePath-fffff2ca","e":false,"i":"","n":"getAbsolutePath","t":"getAbsolutePath(path: String): String","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#incoming-2e6","e":false,"i":"","n":"incoming","t":"incoming(handler: HttpRequest => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#incoming-fffffbee","e":false,"i":"","n":"incoming","t":"incoming(path: String, methods: AnyRef, handler: HttpRequest => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#mountPath-0","e":false,"i":"","n":"mountPath","t":"mountPath: String","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#outgoing-2e6","e":false,"i":"","n":"outgoing","t":"outgoing(filter: HttpResponse => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#post-d21","e":false,"i":"","n":"post","t":"post(path: String, handler: HttpRequest => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#put-d21","e":false,"i":"","n":"put","t":"put(path: String, handler: HttpRequest => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#recover-4a7","e":false,"i":"","n":"recover","t":"recover(handler: (HttpRequest, Throwable) => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#route-d21","e":false,"i":"","n":"route","t":"route(path: String, module: Router => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#route-fffffcda","e":false,"i":"","n":"route","t":"route(path: String, predicate: HttpRequest => Boolean, module: Router => AnyRef): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#trigger-cd5","e":false,"i":"","n":"trigger","t":"trigger[T](hook: AnyRef => T): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/Router.html#websocket-fffff910","e":false,"i":"","n":"websocket","t":"websocket[T](path: String, handler: WebSocket => T): this.type","d":"scurry.http.Router","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#","e":false,"i":"","n":"WebSocket","t":"WebSocket","d":"scurry.http","k":"class","x":""},
{"l":"scurry/http/WebSocket.html#close-94c","e":false,"i":"","n":"close","t":"close(): Unit","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#close-fffff3b3","e":false,"i":"","n":"close","t":"close(code: Int): Unit","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getId-665","e":false,"i":"","n":"getId","t":"getId(): String","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getIdleTimeout-ffffff27","e":false,"i":"","n":"getIdleTimeout","t":"getIdleTimeout(): Int","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getMessageCapacity-ffffff27","e":false,"i":"","n":"getMessageCapacity","t":"getMessageCapacity(): Int","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getPayloadLimit-ffffff27","e":false,"i":"","n":"getPayloadLimit","t":"getPayloadLimit(): Int","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getProtocolVersion-665","e":false,"i":"","n":"getProtocolVersion","t":"getProtocolVersion(): String","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getState-665","e":false,"i":"","n":"getState","t":"getState(): String","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#getTarget-665","e":false,"i":"","n":"getTarget","t":"getTarget(): String","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#isSecure-fffff760","e":false,"i":"","n":"isSecure","t":"isSecure(): Boolean","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#onBinary-6db","e":false,"i":"","n":"onBinary","t":"onBinary[T](handler: (Array[Byte]) => T): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#onClose-6db","e":false,"i":"","n":"onClose","t":"onClose[T](handler: Int => T): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#onError-6db","e":false,"i":"","n":"onError","t":"onError[T](handler: Throwable => T): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#onPing-6db","e":false,"i":"","n":"onPing","t":"onPing[T](handler: (Array[Byte]) => T): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#onPong-6db","e":false,"i":"","n":"onPong","t":"onPong[T](handler: (Array[Byte]) => T): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#onText-6db","e":false,"i":"","n":"onText","t":"onText[T](handler: String => T): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#open-94c","e":false,"i":"","n":"open","t":"open(): Unit","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#ping-afe","e":false,"i":"","n":"ping","t":"ping(data: Array[Byte]): Unit","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#pingAsync-fffff315","e":false,"i":"","n":"pingAsync","t":"pingAsync[T](data: Array[Byte]): CompletableFuture[Unit]","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#pong-afe","e":false,"i":"","n":"pong","t":"pong(data: Array[Byte]): Unit","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#pongAsync-fffff315","e":false,"i":"","n":"pongAsync","t":"pongAsync[T](data: Array[Byte]): CompletableFuture[Unit]","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#send-fffff71f","e":false,"i":"","n":"send","t":"send(message: AnyRef): Unit","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#sendAsync-fffff1c5","e":false,"i":"","n":"sendAsync","t":"sendAsync(message: AnyRef): CompletableFuture[Unit]","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#setIdleTimeout-fffffa54","e":false,"i":"","n":"setIdleTimeout","t":"setIdleTimeout(milliseconds: Int): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#setMessageCapacity-fffffa54","e":false,"i":"","n":"setMessageCapacity","t":"setMessageCapacity(size: Int): this.type","d":"scurry.http.WebSocket","k":"def","x":""},
{"l":"scurry/http/WebSocket.html#setPayloadLimit-fffffa54","e":false,"i":"","n":"setPayloadLimit","t":"setPayloadLimit(length: Int): this.type","d":"scurry.http.WebSocket","k":"def","x":""}];